Importing Libraries

---



In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Reading the File

---

In [ ]:
data = pd.read_csv("IRIS.csv")
print(data)

x = data.iloc[:, :-1].values
print(f"\nThe X values are : {x}")

y = data.iloc[:, -1].values
print(f"\nThe Y Values are : {y}")

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.4)

Scaling

---

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

Training

---

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=2)

Predition

---

In [ ]:
y_pred = classifier.predict(x_test)

Print

---

In [ ]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
result1 = classification_report(y_test, y_pred)
print(f"Classification Report -\n {result1}")

result2 = accuracy_score(y_test, y_pred)
print(f"Accuracy Score - {result2}")

result = confusion_matrix(y_test, y_pred)
print(f"Confusion Score -\n {result}")


Classification Report -
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        24
Iris-versicolor       0.80      1.00      0.89        16
 Iris-virginica       1.00      0.80      0.89        20

       accuracy                           0.93        60
      macro avg       0.93      0.93      0.93        60
   weighted avg       0.95      0.93      0.93        60

Accuracy Score - 0.9333333333333333
Confusion Score -
 [[24  0  0]
 [ 0 16  0]
 [ 0  4 16]]
